import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import ReduxProvider from "@/provider/ReduxProvider";
import ModalProvider from "@/provider/ModalProvider";
import ToastProvider from "@/provider/ToastProvider";
import UploadModalProvider from "@/provider/UploadModalProvider";
import Player from "@/components/Player";
const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify - Music For Everyone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <ReduxProvider>
          <ToastProvider />
          <UploadModalProvider />
          <ModalProvider />
          <Player />
          <Sidebar>{children}</Sidebar>
        </ReduxProvider>
      </body>
    </html>
  );
}
